name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: sudo apt-get install libasound2-dev libgtkmm-3.0-dev libgtksourceviewmm-3.0-dev -y
    - name: make
      run: make
    
